### ISSUE TITLE
Support Appium Python Client 2.7.1

### ISSUE THREAD

**Issue by tuyenlq** [OpenTMI/stf-appium-python-client#19]
Hi team,

I run stf appium python client on robot framework + device farm but i have some problems

Appium CLI : 1.22.3
Appium Python Client 2.7.1
Error :
```
20221027 09:31:00.547 :  INFO : adb(5037): connected to 10.124.60.235:7449
20221027 09:31:00.548 :  INFO : Start Appium with args: -a 127.0.0.1 -p 55941 --allow-insecure chromedriver_autodownload,adb_shell {}
20221027 09:31:02.720 :  WARN : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000252041A4F88>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
20221027 09:32:01.837 :  FAIL : AppiumServiceError: Appium server has started but is not listening on /status within 60000ms timeout. Make sure proper values have been provided to --base-path, --address and --port process arguments.

```
I downgrade Appium Python Client 2.x.x to 1.3.0 it work. Do you have any solution with Appium Python Client 2.x.x ?

Thanks

**Comment by jupe** [comment]
you need to use also appium server 2.x (`npm install appium@next`) . This library expects that server and client are compatible with each other and fetch proper appium api uri from appium package, see: https://github.com/OpenTMI/stf-appium-python-client/blob/6d568611a7167eaa3629dffab006b5799e025859/stf_appium_client/AppiumServer.py#L31 .

**Comment by jupe** [comment]
I guess you get it working, but if not please reopen ticket..
